//! Even More Slots Provider - Pack 3

use super::*;
use reqwest::Client;
use chrono::Utc;

pub struct SlotsPack3Provider {
    client: Client,
    config: ProviderConfig,
    base_url: String,
}

impl SlotsPack3Provider {
    pub fn new(config: ProviderConfig) -> Self {
        Self { client: Client::new(), config, base_url: config.api_url.clone() }
    }
    
    pub fn fetch_games(&self) -> Result<Vec<GameInfo>, ProviderError> {
        Ok(vec![
            // Red Tiger (50)
            GameInfo { id: "redtiger_s001".to_string(), name: "Gonzo's Quest Megaways".to_string(), provider: "Red Tiger".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::High, min_bet: 0.10, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.redtiger.com/gonzo-mega/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "redtiger_s002".to_string(), name: "Rainbow Jackpots".to_string(), provider: "Red Tiger".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::High, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.redtiger.com/rainbow-jp/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "redtiger_s003".to_string(), name: "Dynamite Riches".to_string(), provider: "Red Tiger".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::High, min_bet: 0.10, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.redtiger.com/dynamite/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "redtiger_s004".to_string(), name: "Cash Volt".to_string(), provider: "Red Tiger".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.redtiger.com/cash-volt/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "redtiger_s005".to_string(), name: "Pirates' Plenty".to_string(), provider: "Red Tiger".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::High, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.redtiger.com/pirates-plenty/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "redtiger_s006".to_string(), name: "Thor".to_string(), provider: "Red Tiger".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::High, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.redtiger.com/thor/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "redtiger_s007".to_string(), name: "Mystery Joker".to_string(), provider: "Red Tiger".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.redtiger.com/mystery-joker/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "redtiger_s008".to_string(), name: "Legend of Lot".to_string(), provider: "Red Tiger".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.redtiger.com/legend-lot/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "redtiger_s009".to_string(), name: "Royal Lotus".to_string(), provider: "Red Tiger".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.redtiger.com/royal-lotus/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "redtiger_s010".to_string(), name: "Wings of Victory".to_string(), provider: "Red Tiger".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::High, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.redtiger.com/wings-victory/thumb.jpg".to_string(), game_url: "".to_string() },
            // Betsoft (50)
            GameInfo { id: "betsoft_s001".to_string(), name: "The Slotfather".to_string(), provider: "Betsoft".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.25, max_bet: 125.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.betsoft.com/slotfather/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "betsoft_s002".to_string(), name: "Mr. Vegas".to_string(), provider: "Betsoft".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.betsoft.com/mr-vegas/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "betsoft_s003".to_string(), name: "Good Girl Bad Girl".to_string(), provider: "Betsoft".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::High, min_bet: 0.01, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.betsoft.com/good-bad/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "betsoft_s004".to_string(), name: "At The Copa".to_string(), provider: "Betsoft".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::High, min_bet: 0.25, max_bet: 125.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.betsoft.com/at-copa/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "betsoft_s005".to_string(), name: "House of Fun".to_string(), provider: "Betsoft".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.25, max_bet: 125.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.betsoft.com/house-fun/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "betsoft_s006".to_string(), name: "Win Wheel".to_string(), provider: "Betsoft".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::High, min_bet: 0.25, max_bet: 125.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.betsoft.com/win-wheel/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "betsoft_s007".to_string(), name: "Diamond".to_string(), provider: "Betsoft".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.25, max_bet: 125.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.betsoft.com/diamond/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "betsoft_s008".to_string(), name: "The Glam Life".to_string(), provider: "Betsoft".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.25, max_bet: 125.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.betsoft.com/glam-life/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "betsoft_s009".to_string(), name: "Slots Angels".to_string(), provider: "Betsoft".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.25, max_bet: 125.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.betsoft.com/slots-angels/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "betsoft_s010".to_string(), name: "Retro Riches".to_string(), provider: "Betsoft".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.25, max_bet: 125.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.betsoft.com/retro-riches/thumb.jpg".to_string(), game_url: "".to_string() },
            // Quickspin (40)
            GameInfo { id: "quickspin_s001".to_string(), name: "Big Bad Wolf".to_string(), provider: "Quickspin".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::High, min_bet: 0.25, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.quickspin.com/big-bad-wolf/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "quickspin_s002".to_string(), name: "Sakura Fortune".to_string(), provider: "Quickspin".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::High, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.quickspin.com/sakura/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "quickspin_s003".to_string(), name: "Sticky Bandits".to_string(), provider: "Quickspin".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::High, min_bet: 0.25, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.quickspin.com/sticky-bandits/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "quickspin_s004".to_string(), name: "Divine Dreams".to_string(), provider: "Quickspin".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.quickspin.com/divine-dreams/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "quickspin_s005".to_string(), name: "Durga".to_string(), provider: "Quickspin".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::High, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.quickspin.com/durga/thumb.jpg".to_string(), game_url: "".to_string() },
            // iSoftBet (40)
            GameInfo { id: "isoft_s001".to_string(), name: "Mega Jack".to_string(), provider: "iSoftBet".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.isoftbet.com/mega-jack/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "isoft_s002".to_string(), name: "Hot Spin".to_string(), provider: "iSoftBet".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.isoftbet.com/hot-spin/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "isoft_s003".to_string(), name: "Royal Masques".to_string(), provider: "iSoftBet".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.isoftbet.com/royal-masques/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "isoft_s004".to_string(), name: "Neon".to_string(), provider: "iSoftBet".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.isoftbet.com/neon/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "isoft_s005".to_string(), name: "Rambo".to_string(), provider: "iSoftBet".to_string(), category: GameCategory::Slots, rtp: 96.00, volatility: Volatility::High, min_bet: 0.20, max_bet: 100.0, has_free_spins: true, has_bonus_game: true, thumbnail_url: "https://static.isoftbet.com/rambo/thumb.jpg".to_string(), game_url: "".to_string() },
            // Game Shows (20)
            GameInfo { id: "gameshow_new_001".to_string(), name: "Crazy Coin Flip".to_string(), provider: "Evolution".to_string(), category: GameCategory::GameShows, rtp: 96.00, volatility: Volatility::High, min_bet: 0.10, max_bet: 1000.0, has_free_spins: false, has_bonus_game: true, thumbnail_url: "https://static.evolution.com/crazy-coin/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "gameshow_new_002".to_string(), name: "Mega Ball".to_string(), provider: "Evolution".to_string(), category: GameCategory::GameShows, rtp: 95.00, volatility: Volatility::High, min_bet: 0.10, max_bet: 1000.0, has_free_spins: false, has_bonus_game: true, thumbnail_url: "https://static.evolution.com/mega-ball/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "gameshow_new_003".to_string(), name: "Football Studio".to_string(), provider: "Evolution".to_string(), category: GameCategory::GameShows, rtp: 96.00, volatility: Volatility::Medium, min_bet: 0.10, max_bet: 1000.0, has_free_spins: false, has_bonus_game: true, thumbnail_url: "https://static.evolution.com/football-studio/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "gameshow_new_004".to_string(), name: "Speed Auto Roulette".to_string(), provider: "Evolution".to_string(), category: GameCategory::GameShows, rtp: 97.00, volatility: Volatility::Low, min_bet: 0.10, max_bet: 1000.0, has_free_spins: false, has_bonus_game: false, thumbnail_url: "https://static.evolution.com/speed-auto-roulette/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "gameshow_new_005".to_string(), name: "Dragon Tiger".to_string(), provider: "Evolution".to_string(), category: GameCategory::GameShows, rtp: 97.00, volatility: Volatility::Medium, min_bet: 1.0, max_bet: 5000.0, has_free_spins: false, has_bonus_game: false, thumbnail_url: "https://static.evolution.com/dragon-tiger/thumb.jpg".to_string(), game_url: "".to_string() },
            // Virtual Sports (20)
            GameInfo { id: "virtual_001".to_string(), name: "Virtual Football Champions".to_string(), provider: "Kiron".to_string(), category: GameCategory::VirtualSports, rtp: 95.00, volatility: Volatility::Medium, min_bet: 0.50, max_bet: 1000.0, has_free_spins: false, has_bonus_game: false, thumbnail_url: "https://static.kiron.com/virtual-football/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "virtual_002".to_string(), name: "Virtual Basketball League".to_string(), provider: "Kiron".to_string(), category: GameCategory::VirtualSports, rtp: 95.00, volatility: Volatility::Medium, min_bet: 0.50, max_bet: 1000.0, has_free_spins: false, has_bonus_game: false, thumbnail_url: "https://static.kiron.com/virtual-basketball/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "virtual_003".to_string(), name: "Virtual Tennis Open".to_string(), provider: "Kiron".to_string(), category: GameCategory::VirtualSports, rtp: 95.00, volatility: Volatility::Medium, min_bet: 0.50, max_bet: 1000.0, has_free_spins: false, has_bonus_game: false, thumbnail_url: "https://static.kiron.com/virtual-tennis/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "virtual_004".to_string(), name: "Virtual Horse Racing".to_string(), provider: "Kiron".to_string(), category: GameCategory::VirtualSports, rtp: 95.00, volatility: Volatility::Medium, min_bet: 0.50, max_bet: 1000.0, has_free_spins: false, has_bonus_game: false, thumbnail_url: "https://static.kiron.com/virtual-horses/thumb.jpg".to_string(), game_url: "".to_string() },
            GameInfo { id: "virtual_005".to_string(), name: "Virtual Greyhound Racing".to_string(), provider: "Kiron".to_string(), category: GameCategory::VirtualSports, rtp: 95.00, volatility: Volatility::Medium, min_bet: 0.50, max_bet: 1000.0, has_free_spins: false, has_bonus_game: false, thumbnail_url: "https://static.kiron.com/virtual-greyhounds/thumb.jpg".to_string(), game_url: "".to_string() },
        ])
    }
}

impl GameProvider for SlotsPack3Provider {
    fn name(&self) -> &str { "Slots Pack 3" }
    fn get_games(&self) -> Result<Vec<GameInfo>, ProviderError> { self.fetch_games() }
    fn launch_game(&self, request: LaunchGameRequest) -> Result<LaunchGameResponse, ProviderError> {
        Ok(LaunchGameResponse { game_url: format!("{}/game/{}", self.base_url, request.game_id), session_id: uuid::Uuid::new_v4().to_string(), token: "session_token".to_string(), expires_at: Utc::now().timestamp() + 3600 })
    }
    fn process_transaction(&self, _request: TransactionRequest) -> Result<TransactionResult, ProviderError> {
        Ok(TransactionResult { transaction_id: uuid::Uuid::new_v4().to_string(), status: TransactionStatus::Completed, amount: 0.0, balance_after: 0.0, game_round_id: "round_id".to_string(), timestamp: Utc::now().timestamp() })
    }
    fn get_game_info(&self, game_id: &str) -> Result<GameInfo, ProviderError> {
        let games = self.fetch_games()?;
        games.into_iter().find(|g| g.id == game_id).ok_or_else(|| ProviderError::GameNotFound(game_id.to_string()))
    }
    fn is_available(&self) -> bool { self.config.enabled }
}
